name: Output information
on: workflow_dispatch
jobs:
  output:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Output information
        run: echo "${{ toJSON(github) }}"